version: 2
jobs:
  unit-tests:
    docker:
      - image: php:7.2-cli-alpine

    working_directory: /framework

    steps:
      - checkout

      - run: ./.circleci/scripts/bootstrap.sh

      - restore_cache:
          keys:
          - deps-{{ checksum "composer.json" }}
          - deps-

      - run: /composer/composer.phar install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: deps-{{ checksum "composer.json" }}

      - run: ./vendor/bin/phpunit

workflows:
  version: 2

  unit-tests:
    jobs:
      - unit-tests