site_name: GraphQL Framework
theme: readthedocs
pages:
  - 'GraphQL Framework': 'index.md'
  - 'Principles & Architecture': 'principles.md'
  - 'Getting Started': 'getting-started.md'
  - 'Configuration': 'configuration.md'
  - 'Controllers': 'controllers.md'
  - 'Fetch Adapters': 'fetch-adapter.md'
  - 'Filters': 'filters.md'
  - 'Entry Point': 'entry.md'
  - 'Development Mode': 'development-mode.md'
  - 'Schema Generator': 'generator.md'
  - 'Type Registry': 'type-registry.md'
  - 'Cache': 'cache.md'
site_dir: '../docs'