site_name: GraphQL Framework
theme: readthedocs
pages:
  - 'GraphQL Framework': 'index.md'
  - 'Getting Started': 'getting-started.md'
  - 'Configuration': 'configuration.md'
  - 'Controllers': 'controllers.md'
  - 'Entry Point': 'entry.md'
  - 'Schema Generator': 'generator.md'